'use strict';

// End-to-end tests for tools/scanVideoWithOcr.js.
//
// These tests spawn the CLI as a subprocess (so the actual ffmpeg + OCR
// pipeline runs end-to-end) against the synthetic fixture generated by
// `node tools/buildSyntheticWhiteboardVideo.js`. They auto-skip when the
// fixture or a working ffmpeg binary is not available.
//
// To run:
//   1. node tools/buildSyntheticWhiteboardVideo.js   # one-off
//   2. node --test test/scanVideoWithOcr.e2e.test.js
//
// What we verify:
//   - whiteboard output_kind produces a status:'done' JSON log and a PNG
//     under outputRoot/screenshots/ named `YYYYMMDD_ps.png`
//   - snapshot output_kind produces a status:'done' JSON log and a PNG
//     under outputRoot/snapshots/ named `revere_YYYYMMDD.png`
//   - both output_kinds parse via parseArgs() into the same path/root/kind

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');

const { parseArgs } = require('../src/video/ocrScanArgs');

const WORKSPACE_ROOT = path.resolve(__dirname, '..');
const FIXTURE_VIDEO = path.join(WORKSPACE_ROOT, 'test', 'fixtures', 'local_20260104_sample_real.mp4');
const FIXTURE_TEXT_HEAVY_VIDEO = path.join(WORKSPACE_ROOT, 'test', 'fixtures', 'local_20260104_sample_text_heavy.mp4');

function detectFfmpeg() {
  if (process.env.FFMPEG_BIN && fs.existsSync(process.env.FFMPEG_BIN)) {
    return process.env.FFMPEG_BIN;
  }

  const candidates = [
    'C:/ffmpeg/bin/ffmpeg.exe',
    'C:/Program Files/ffmpeg/bin/ffmpeg.exe'
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }

  const wingetRoot = path.join(os.homedir(), 'AppData', 'Local', 'Microsoft', 'WinGet', 'Packages');
  if (fs.existsSync(wingetRoot)) {
    const matches = fs.readdirSync(wingetRoot, { withFileTypes: true })
      .filter((entry) => entry.isDirectory() && entry.name.startsWith('Gyan.FFmpeg'))
      .flatMap((entry) => {
        const vendorRoot = path.join(wingetRoot, entry.name);
        return fs.readdirSync(vendorRoot, { withFileTypes: true })
          .filter((child) => child.isDirectory())
          .map((child) => path.join(vendorRoot, child.name, 'bin', 'ffmpeg.exe'));
      })
      .filter((candidate) => fs.existsSync(candidate))
      .sort();
    if (matches.length) {
      return matches[matches.length - 1];
    }
  }

  return null;
}

function freshOutputRoot(label) {
  return fs.mkdtempSync(path.join(WORKSPACE_ROOT, 'data', `video_ocr_e2e_${label}_`));
}

function runScanCli({ outputRoot, outputKind, ffmpegBin, videoPath, extraArgs = [] }) {
  const targetVideo = videoPath || FIXTURE_VIDEO;
  const args = [
    'tools/scanVideoWithOcr.js',
    '--video', targetVideo,
    '--output-root', outputRoot,
    '--output-kind', outputKind,
    '--fps', '1',
    '--prefilter-threshold', '6',
    '--prefilter-min-frames', '1',
    '--prefilter-max-frames', '4',
    '--progress-interval', '1',
    '--top-candidates', '3',
    '--keep-frames',
    '--skip-keyframes',
    '--confusion-radius', '1',
    ...extraArgs
  ];
  if (ffmpegBin) {
    args.push('--ffmpeg-bin', ffmpegBin);
  }
  return spawnSync('node', args, {
    cwd: WORKSPACE_ROOT,
    encoding: 'utf8',
    stdio: 'pipe',
    maxBuffer: 16 * 1024 * 1024
  });
}

function findProbeLog(outputRoot, outputKind) {
  const logsDirectory = path.join(outputRoot, 'ocr_probe', 'logs');
  if (!fs.existsSync(logsDirectory)) {
    return null;
  }

  const candidates = fs.readdirSync(logsDirectory).filter((name) => name.endsWith(`_${outputKind}.json`));
  if (!candidates.length) {
    return null;
  }

  const probeLogPath = path.join(logsDirectory, candidates[0]);
  return JSON.parse(fs.readFileSync(probeLogPath, 'utf8'));
}

const ffmpegBin = detectFfmpeg();
const fixtureAvailable = fs.existsSync(FIXTURE_VIDEO);

test('end-to-end whiteboard scan produces a status:done screenshot', { skip: !ffmpegBin || !fixtureAvailable }, () => {
  assert.ok(ffmpegBin, 'ffmpeg binary must be resolvable for this test to run');
  assert.ok(fixtureAvailable, `Synthetic fixture missing: ${FIXTURE_VIDEO}. Run: node tools/buildSyntheticWhiteboardVideo.js`);

  const outputRoot = freshOutputRoot('whiteboard');
  try {
    const result = runScanCli({ outputRoot, outputKind: 'whiteboard', ffmpegBin });
    assert.equal(result.status, 0, `scan CLI failed:\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);

    const probeLog = findProbeLog(outputRoot, 'whiteboard');
    assert.ok(probeLog, `expected a probe log under ${outputRoot}/ocr_probe/logs/`);
    assert.equal(probeLog.status, 'done');
    assert.ok(probeLog.output_path, 'status:done must include an output_path');
    assert.ok(fs.existsSync(probeLog.output_path), `output_path file missing: ${probeLog.output_path}`);
    assert.ok(fs.statSync(probeLog.output_path).size > 0, 'output_path file must be non-empty');
    assert.equal(probeLog.output_kind, 'whiteboard');
    assert.ok(probeLog.ocr_frame_count >= 1, 'expected at least one OCR frame');
    assert.ok(Array.isArray(probeLog.top_candidates));
    assert.ok(probeLog.top_candidates.length <= 3);

    const expectedScreenPath = path.join(outputRoot, 'screenshots', '20260104_ps.png');
    assert.equal(probeLog.output_path, expectedScreenPath);

    // The whiteboard screenshot must be discoverable by discoverWhiteboardScreenshots
    const { discoverWhiteboardScreenshots } = require('../src/io/discoverWhiteboardScreenshots');
    return discoverWhiteboardScreenshots(path.join(outputRoot, 'screenshots')).then((entries) => {
      assert.equal(entries.length, 1);
      assert.equal(entries[0].dateKey, '20260104');
    });
  } finally {
    fs.rmSync(outputRoot, { recursive: true, force: true });
  }
});

test('end-to-end snapshot scan produces a revere_YYYYMMDD.png screenshot', { skip: !ffmpegBin || !fixtureAvailable }, () => {
  assert.ok(ffmpegBin, 'ffmpeg binary must be resolvable for this test to run');
  assert.ok(fixtureAvailable, `Synthetic fixture missing: ${FIXTURE_VIDEO}. Run: node tools/buildSyntheticWhiteboardVideo.js`);

  const outputRoot = freshOutputRoot('snapshot');
  try {
    const result = runScanCli({ outputRoot, outputKind: 'snapshot', ffmpegBin });
    assert.equal(result.status, 0, `scan CLI failed:\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);

    const probeLog = findProbeLog(outputRoot, 'snapshot');
    assert.ok(probeLog, `expected a probe log under ${outputRoot}/ocr_probe/logs/`);
    assert.equal(probeLog.status, 'done');
    assert.equal(probeLog.output_kind, 'snapshot');
    assert.ok(probeLog.output_path, 'status:done must include an output_path');
    assert.ok(fs.existsSync(probeLog.output_path), `output_path file missing: ${probeLog.output_path}`);

    const expectedSnapPath = path.join(outputRoot, 'snapshots', 'revere_20260104.png');
    assert.equal(probeLog.output_path, expectedSnapPath);
  } finally {
    fs.rmSync(outputRoot, { recursive: true, force: true });
  }
});

test('parseArgs produces the same options that the CLI parses from argv', () => {
  const argv = [
    '--video', FIXTURE_VIDEO,
    '--output-root', './tmp-root',
    '--output-kind', 'whiteboard',
    '--fps', '1',
    '--prefilter-threshold', '6',
    '--prefilter-min-frames', '1',
    '--prefilter-max-frames', '4',
    '--progress-interval', '1',
    '--top-candidates', '3',
    '--keep-frames',
    '--skip-keyframes',
    '--confusion-radius', '2'
  ];
  const options = parseArgs(argv, { defaultOutputRoot: path.join(WORKSPACE_ROOT, 'data', 'ocr_probe_test_default') });

  assert.equal(options.videoPath, path.resolve(FIXTURE_VIDEO));
  assert.equal(options.outputKind, 'whiteboard');
  assert.equal(options.fps, 1);
  assert.equal(options.prefilterThreshold, 6);
  assert.equal(options.prefilterMinFrames, 1);
  assert.equal(options.prefilterMaxFrames, 4);
  assert.equal(options.progressInterval, 1);
  assert.equal(options.topCandidates, 3);
  assert.equal(options.keepFrames, true);
  assert.equal(options.skipKeyframes, true);
  assert.equal(options.confusionRadius, 2);
});

test('CLI writes status:error log when the input file is not a real video', { skip: !ffmpegBin }, () => {
  const stubFixture = path.join(WORKSPACE_ROOT, 'test', 'fixtures', 'local_20260104_sample.mp4');
  assert.ok(fs.existsSync(stubFixture), `expected stub fixture at ${stubFixture}`);

  const outputRoot = freshOutputRoot('error');
  try {
    runScanCli({ outputRoot, outputKind: 'whiteboard', ffmpegBin, videoPath: stubFixture });

    const logsDirectory = path.join(outputRoot, 'ocr_probe', 'logs');
    const logsContents = fs.existsSync(logsDirectory) ? fs.readdirSync(logsDirectory) : [];
    assert.ok(logsContents.length >= 1, `expected at least one probe log under ${logsDirectory}; got: ${JSON.stringify(logsContents)}`);

    // Pick the error log (status:'error') if more than one exists.
    let chosen = null;
    for (const name of logsContents) {
      if (!name.endsWith('_whiteboard.json')) continue;
      const parsed = JSON.parse(fs.readFileSync(path.join(logsDirectory, name), 'utf8'));
      if (parsed.status === 'error') {
        chosen = parsed;
        break;
      }
    }
    assert.ok(chosen, `expected at least one error-status log under ${logsDirectory}; saw: ${logsContents.join(', ')}`);
    assert.match(chosen.message, /preflight/i);
  } finally {
    fs.rmSync(outputRoot, { recursive: true, force: true });
  }
});

test('text-heavy scan captures multi-screen output with enriched JSON log', { skip: !ffmpegBin || !fs.existsSync(FIXTURE_TEXT_HEAVY_VIDEO) }, () => {
  assert.ok(ffmpegBin, 'ffmpeg binary must be resolvable for this test to run');
  assert.ok(fs.existsSync(FIXTURE_TEXT_HEAVY_VIDEO), `Text-heavy fixture missing: ${FIXTURE_TEXT_HEAVY_VIDEO}. Run: node tools/buildSyntheticWhiteboardVideo.js`);

  const outputRoot = freshOutputRoot('text-heavy');
  try {
    const result = runScanCli({
      outputRoot,
      outputKind: 'whiteboard',
      ffmpegBin,
      videoPath: FIXTURE_TEXT_HEAVY_VIDEO,
      extraArgs: ['--max-captures', '2']
    });
    assert.equal(result.status, 0, `scan CLI failed:\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);

    const probeLog = findProbeLog(outputRoot, 'whiteboard');
    assert.ok(probeLog, `expected a probe log under ${outputRoot}/ocr_probe/logs/`);
    assert.ok(['done', 'review'].includes(probeLog.status), `expected done|review, got ${probeLog.status}`);

    // Multi-capture: at least 1 capture saved, plus the legacy output_path field
    assert.ok(Array.isArray(probeLog.captures), 'expected captures array');
    assert.ok(probeLog.captured_count >= 1, `expected captured_count >= 1, got ${probeLog.captured_count}`);
    assert.equal(probeLog.captured_count, probeLog.captures.length);

    for (const capture of probeLog.captures) {
      assert.ok(capture.output_path, 'each capture must have an output_path');
      assert.ok(fs.existsSync(capture.output_path), `capture file missing: ${capture.output_path}`);
      assert.ok(capture.score > 0, `capture score should be > 0, got ${capture.score}`);
      assert.ok(typeof capture.ocr_text_snippet === 'string', 'capture must include ocr_text_snippet');
      assert.ok(typeof capture.ocr_text === 'string', 'capture must include full ocr_text');
      assert.ok(Array.isArray(capture.tickers), 'capture must include tickers array');
      assert.ok(typeof capture.phash === 'string' && capture.phash.length === 16, `phash must be 16-char hex, got ${capture.phash}`);
      assert.ok(capture.prefilter_stats && typeof capture.prefilter_stats.brightRatio === 'number',
        'capture must include prefilter_stats.brightRatio');
      assert.ok(typeof capture.timestamp_hms === 'string', 'capture must include timestamp_hms');
      assert.ok(Array.isArray(capture.confusion_with_nearby), 'capture must include confusion_with_nearby array');
      assert.ok(Array.isArray(capture.parsed_observations), 'capture must include parsed_observations array');
      assert.ok(['structured_whiteboard', 'dmi', 'tale_of_the_tape', 'unknown_text', 'chart', 'unknown'].includes(capture.screen_layout),
        `unexpected screen_layout: ${capture.screen_layout}`);
      assert.ok(Array.isArray(capture.issue_codes), 'capture must include issue_codes array');
      assert.equal(capture.output_kind, 'whiteboard');
      // --skip-keyframes was passed; the keyframe lookup must be null for every capture.
      assert.equal(capture.nearest_ffmpeg_keyframe_ts, null);
    }

    // OCR engine metadata is captured once per scan at the probe-log top level.
    assert.ok(probeLog.ocr_engine_metadata, 'probe log must include ocr_engine_metadata');
    assert.equal(probeLog.ocr_engine_metadata.language, 'eng');
    assert.ok(typeof probeLog.ocr_engine_metadata.tesseract_version === 'string');
    assert.equal(probeLog.nearest_ffmpeg_keyframe_lookups_skipped, true);

    // The number of saved PNG files under screenshots/ must match captures.length
    const screenshotsDirectory = path.join(outputRoot, 'screenshots');
    const savedFiles = fs.existsSync(screenshotsDirectory)
      ? fs.readdirSync(screenshotsDirectory).filter((name) => name.endsWith('.png'))
      : [];
    assert.equal(savedFiles.length, probeLog.captures.length,
      `expected ${probeLog.captures.length} PNG(s) under screenshots/, got ${savedFiles.length}`);

    // Strong threshold and review threshold are now persisted for diagnostic visibility
    assert.equal(probeLog.strong_threshold, 6);
    assert.equal(probeLog.review_threshold, 4);
    assert.equal(probeLog.max_captures_per_video, 2);
  } finally {
    fs.rmSync(outputRoot, { recursive: true, force: true });
  }
});
