#!/usr/bin/env bash
# Dry run for the local-video flow.
#
# Exercises:
#   init -> import-local -> scan -> status
#
# Uses the synthetic MP4 + white reference PNG generated by
# tools/buildSyntheticWhiteboardVideo.js and the real ffmpeg binary.
#
# Writes under a sandboxed pipeline-root in
# ./data/video_pipeline_dryrun_local_<pid>/ and never touches the read-only
# asset folder.
#
# Exits non-zero if any assertion fails.

set -euo pipefail

WORKSPACE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VIDEO_FIXTURE="$WORKSPACE_ROOT/test/fixtures/local_20260104_sample_real.mp4"
REFERENCE_FIXTURE="$WORKSPACE_ROOT/test/fixtures/references/reference_board_white.png"
PIPELINE_ROOT="$WORKSPACE_ROOT/data/video_pipeline_dryrun_local_$$"
# The import-local worker sorts files alphabetically and applies --limit.
# `local_20260104_sample.mp4` (the OCR-error stub) sorts BEFORE
# `local_20260104_sample_real.mp4`, so we copy the synthetic video to a
# dedicated scratch directory that contains only that one file.
VIDEO_SCRATCH_DIR="$WORKSPACE_ROOT/data/video_pipeline_dryrun_local_scratch_$$"
VIDEO_SCRATCH="$VIDEO_SCRATCH_DIR/local_20260104_sample_real.mp4"

echo "[dryrun-local] workspace: $WORKSPACE_ROOT"
echo "[dryrun-local] pipeline root: $PIPELINE_ROOT"

if [[ ! -f "$VIDEO_FIXTURE" ]]; then
  echo "[dryrun-local] FAIL: synthetic video missing at $VIDEO_FIXTURE" >&2
  echo "[dryrun-local] Run: node tools/buildSyntheticWhiteboardVideo.js" >&2
  exit 1
fi
if [[ ! -f "$REFERENCE_FIXTURE" ]]; then
  echo "[dryrun-local] FAIL: white reference missing at $REFERENCE_FIXTURE" >&2
  echo "[dryrun-local] Run: node tools/buildSyntheticWhiteboardVideo.js" >&2
  exit 1
fi

mkdir -p "$VIDEO_SCRATCH_DIR"
cp "$VIDEO_FIXTURE" "$VIDEO_SCRATCH"

# Find an ffmpeg binary on PATH or under WinGet
FFMPEG_BIN="${FFMPEG_BIN:-}"
if [[ -z "$FFMPEG_BIN" ]]; then
  if command -v ffmpeg >/dev/null 2>&1; then
    FFMPEG_BIN="$(command -v ffmpeg)"
  elif [[ -f "C:/ffmpeg/bin/ffmpeg.exe" ]]; then
    FFMPEG_BIN="C:/ffmpeg/bin/ffmpeg.exe"
  elif [[ -f "C:/Program Files/ffmpeg/bin/ffmpeg.exe" ]]; then
    FFMPEG_BIN="C:/Program Files/ffmpeg/bin/ffmpeg.exe"
  else
    winget_root="$HOME/AppData/Local/Microsoft/WinGet/Packages"
    if [[ -d "$winget_root" ]]; then
      candidate="$(find "$winget_root" -path '*/Gyan.FFmpeg*/bin/ffmpeg.exe' 2>/dev/null | sort | tail -n 1 || true)"
      if [[ -n "$candidate" ]]; then
        FFMPEG_BIN="$candidate"
      fi
    fi
  fi
fi

if [[ -z "$FFMPEG_BIN" ]] || [[ ! -f "$FFMPEG_BIN" ]]; then
  echo "[dryrun-local] FAIL: ffmpeg not found. Install ffmpeg or set FFMPEG_BIN." >&2
  exit 1
fi
echo "[dryrun-local] ffmpeg: $FFMPEG_BIN"

cleanup() {
  rm -rf "$PIPELINE_ROOT"
  rm -rf "$VIDEO_SCRATCH_DIR"
}
trap cleanup EXIT

DRIVER="$WORKSPACE_ROOT/tools/runWhiteboardWorker.js"

echo "[dryrun-local] step 1/4: init"
node "$DRIVER" init --pipeline-root "$PIPELINE_ROOT" >/dev/null

echo "[dryrun-local] step 2/4: import-local"
import_output="$(node "$DRIVER" import-local \
  --pipeline-root "$PIPELINE_ROOT" \
  --video-dir "$VIDEO_SCRATCH_DIR" \
  --limit 1)"
imported="$(echo "$import_output" | node -e 'let buf="";process.stdin.on("data",(c)=>buf+=c);process.stdin.on("end",()=>{try{console.log(JSON.parse(buf).imported||0)}catch(_){console.log(0)}})')"
if [[ "$imported" != "1" ]]; then
  echo "[dryrun-local] FAIL: import-local expected 1 row, got $imported" >&2
  echo "$import_output" >&2
  exit 1
fi

echo "[dryrun-local] step 3/4: scan"
scan_output="$(node "$DRIVER" scan \
  --pipeline-root "$PIPELINE_ROOT" \
  --reference-dir "$WORKSPACE_ROOT/test/fixtures/references" \
  --ffmpeg-bin "$FFMPEG_BIN" \
  --limit 1 \
  --sample-fps 1 \
  --similarity-threshold 0.9 \
  --review-threshold 0.7 \
  --min-window-length 1 \
  --score-margin 0.05 \
  --candidate-limit 3)"
scan_status="$(echo "$scan_output" | node -e 'let buf="";process.stdin.on("data",(c)=>buf+=c);process.stdin.on("end",()=>{try{console.log(JSON.parse(buf).status||"unknown")}catch(_){console.log("unknown")}})')"
if [[ "$scan_status" != "ok" ]]; then
  echo "[dryrun-local] FAIL: scan expected status 'ok', got '$scan_status'" >&2
  echo "$scan_output" >&2
  exit 1
fi

echo "[dryrun-local] step 4/4: status"
status_output="$(node "$DRIVER" status --pipeline-root "$PIPELINE_ROOT" --list-limit 5)"
done_count="$(echo "$status_output" | node -e 'let buf="";process.stdin.on("data",(c)=>buf+=c);process.stdin.on("end",()=>{try{console.log((JSON.parse(buf).video_counts||{}).done||0)}catch(_){console.log(0)}})')"
errored_count="$(echo "$status_output" | node -e 'let buf="";process.stdin.on("data",(c)=>buf+=c);process.stdin.on("end",()=>{try{console.log((JSON.parse(buf).video_counts||{}).error||0)}catch(_){console.log(0)}})')"
if [[ "$done_count" != "1" ]]; then
  echo "[dryrun-local] FAIL: status expected video_counts.done=1, got $done_count" >&2
  echo "$status_output" >&2
  exit 1
fi
if [[ "$errored_count" != "0" ]]; then
  echo "[dryrun-local] FAIL: status expected video_counts.error=0, got $errored_count" >&2
  echo "$status_output" >&2
  exit 1
fi

# Verify a whiteboard PNG was extracted into screenshots/
screenshots_dir="$PIPELINE_ROOT/screenshots"
screen_files="$(find "$screenshots_dir" -name '20260104_ps*.jpg' 2>/dev/null | wc -l)"
if [[ "$screen_files" != "1" ]]; then
  echo "[dryrun-local] FAIL: expected 1 whiteboard screenshot under $screenshots_dir, got $screen_files" >&2
  exit 1
fi

echo "[dryrun-local] OK: imported=1, scan_status=ok, done=1, errored=0, screenshot=20260104_ps.jpg"
