'use strict';

/**
 * export_youtube_cookies.js
 *
 * Uses Playwright to connect to Chrome via Chrome DevTools Protocol (CDP) remote
 * debugging port, which CAN extract cookies from the actual Chrome session without
 * needing to decrypt them via DPAPI. Chrome must be running with:
 *   chrome --remote-debugging-port=9222
 *
 * Usage:
 *   # First, launch Chrome with debugging (or find existing debuggable instance):
 *   # chrome --remote-debugging-port=9222
 *   #
 *   # Then run:
 *   node tools/export_youtube_cookies.js [--output cookies.txt]
 *
 * Or: use Playwright's own browser (fresh profile) to navigate to YouTube and
 * save the cookies to a Netscape-format file for yt-dlp.
 */

const { chromium } = require('playwright');
const fs = require('fs');

const argv = process.argv.slice(2);
const outputPath = argv.includes('--output') ? argv[argv.indexOf('--output') + 1] : 'data/video_pipeline/downloads_1080p/youtubeCookies.txt';

// Try CDP connection to Chrome, fall back to fresh Playwright browser
async function tryCdpChrome() {
  try {
    // Try to connect to Chrome's remote debugging port
    const browser = await chromium.connectOverCDP('http://localhost:9222');
    const contexts = browser.contexts();
    if (!contexts.length) throw new Error('No Chrome contexts found');
    const page = await contexts[0].newPage();
    await page.goto('https://www.youtube.com', { waitUntil: 'networkidle', timeout: 15000 });
    const cookies = await contexts[0].cookies(['https://www.youtube.com']);
    await browser.close();
    return cookies;
  } catch (e) {
    return null; // Fall through to fresh browser
  }
}

async function main() {
  console.log('[cookies] Attempting to extract YouTube cookies...');

  // Try CDP first (real Chrome session)
  let cookies = await tryCdpChrome();
  let source = 'Chrome via CDP';

  if (!cookies || cookies.length < 3) {
    // Fall back: use Playwright's own browser, go to YouTube, click "Accept" on cookie banner
    console.log('[cookies] CDP failed or insufficient cookies — using fresh Playwright browser');
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({
      // Spoof a desktop browser to get full YouTube
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'
    });
    const page = await context.newPage();
    await page.goto('https://www.youtube.com', { waitUntil: 'networkidle', timeout: 30000 });

    // Try to dismiss cookie banner if present
    try {
      const acceptBtn = page.getByText('Accept all');
      if (await acceptBtn.isVisible({ timeout: 2000 })) {
        await acceptBtn.click();
        await page.waitForTimeout(500);
      }
    } catch {}

    cookies = await context.cookies(['https://www.youtube.com']);
    source = 'Fresh Playwright browser';
    await browser.close();
  }

  console.log(`[cookies] Extracted ${cookies.length} cookies from ${source}`);

  if (!cookies.length) {
    console.error('[cookies] No cookies found. Make sure you are logged into YouTube in Chrome');
    console.error('[cookies] with Chrome running as: chrome --remote-debugging-port=9222');
    process.exit(1);
  }

  // Write as Netscape format
  const lines = ['# Netscape HTTP Cookie File', '# Generated by export_youtube_cookies.js — use with yt-dlp --cookies'];
  for (const c of cookies) {
    const domain = c.domain.startsWith('.') ? c.domain : (c.domain.includes('.') ? c.domain : '.' + c.domain);
    const flag = c.secure ? 'TRUE' : 'FALSE';
    const expiry = c.expires ? Math.floor(c.expires) : 0;
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
  }

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
  const size = fs.statSync(outputPath).size;
  console.log(`[cookies] Wrote ${cookies.length} cookies to: ${outputPath} (${size} bytes)`);
  console.log('[cookies] To use with yt-dlp:');
  console.log(`[cookies]   node tools/downloadQmg1080p.js --cookies ${outputPath} --limit 50`);
}

main().catch(err => {
  console.error('[cookies] Fatal:', err.message);
  process.exit(1);
});
